apps/candidate/urls.py
from django.urls import path
from . import views

app_name = "candidate"
urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("update-password/", views.update_password, name="update_password"),
    path("apply/", views.apply_for_position, name="apply_for_position"),
    path("applied-jobs/", views.candidate_jobs, name="applied_jobs"),
    path("undo/", views.undo_for_position, name="undo_for_position"),
]

job_application_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as core_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        # core urls
        path("", core_views.index, name="index"),
        path("register/", core_views.register, name="register"),
        path("login/", core_views.login, name="login"),
        path("logout/", core_views.logout, name="logout"),
        # candidate urls
        path("candidate/", include("apps.candidate.urls")),
        # password reset urls derived from core Django
        path(
            "password/password_reset/done/",
            PasswordResetDoneView.as_view(
                template_name="password/password_reset_done.html",
            ),
            name="password_reset_done",
        ),
        path(
            "password/reset/<uidb64>/<token>/",
            PasswordResetConfirmView.as_view(
                template_name="password/password_reset_confirm.html",
            ),
            name="password_reset_confirm",
        ),
        path(
            "password/reset/done/",
            PasswordResetCompleteView.as_view(
                template_name="password/password_reset_complete.html",
            ),
            name="password_reset_complete",
        ),
        path("password/reset", core_views.password_reset, name="password_reset")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

templates/utilities/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %} {{get_app_name}} {% endblock %}</title>
    <link
      rel="stylesheet"
      href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'toast/toast.min.css' %}">
    <script src="{% static 'toast/toast.min.js' %}"></script>
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
          <script>
              new Toast({
                  message: '{{ message }}',
                  type: '{{ message.tags }}'
              });

          </script>
      {% endfor %}
    {% endif %}
    
    {% if request.user.is_authenticated %}
        {% include 'utilities/header.html' %}
    {% endif %}

    {% block body %}

    {% endblock %}
    <script src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/utilities/header.html
{% load static %}
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'index' %}">{{get_app_name}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/' %} active {% endif %}" aria-current="page" href="{% url 'index' %}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/candidate/profile/' %} active {% endif %}" aria-current="page" href="{% url 'candidate:profile' %}">Profile</a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if request.path == '/candidate/applied-jobs/' %} active {% endif %}" aria-current="page" href="{% url 'candidate:applied_jobs' %}">Applied Jobs</a>
          </li>
        </ul>
        <form class="d-flex" action="{% url 'logout' %}" method="get">
          <button class="btn btn-outline-danger" type="submit">Log Out</button>
        </form>
      </div>
    </div>
  </nav>