apps/candidate/urls.py
from django.urls import path
from . import views

app_name = "candidate"
urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("update-password/", views.update_password, name="update_password"),
    path("apply/", views.apply_for_position, name="apply_for_position"),
    path("applied-jobs/", views.candidate_jobs, name="applied_jobs"),
    path("undo/", views.undo_for_position, name="undo_for_position"),
]

job_application_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as core_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        # core urls
        path("", core_views.index, name="index"),
        path("register/", core_views.register, name="register"),
        path("login/", core_views.login, name="login"),
        path("logout/", core_views.logout, name="logout"),
        # candidate urls
        path("candidate/", include("apps.candidate.urls")),
        # password reset urls derived from core Django
        path(
            "password/password_reset/done/",
            PasswordResetDoneView.as_view(
                template_name="password/password_reset_done.html",
            ),
            name="password_reset_done",
        ),
        path(
            "password/reset/<uidb64>/<token>/",
            PasswordResetConfirmView.as_view(
                template_name="password/password_reset_confirm.html",
            ),
            name="password_reset_confirm",
        ),
        path(
            "password/reset/done/",
            PasswordResetCompleteView.as_view(
                template_name="password/password_reset_complete.html",
            ),
            name="password_reset_complete",
        ),
        path("password/reset", core_views.password_reset, name="password_reset")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

apps/candidate/models.py
from django.db import models
from django.contrib.auth.models import User
from unidecode import unidecode
from django.template.defaultfilters import slugify
from django.contrib import admin


class CandidateProfile(models.Model):
    user = models.OneToOneField(User, models.CASCADE, related_name="candidate_profile")
    bio = models.TextField()
    skills = models.ManyToManyField("candidate.JobSkill", "candidates")

    class Meta:
        verbose_name = "Candidate Profile"
        verbose_name_plural = "Candidate Profiles"

    def __str__(self):
        return self.user.username


class JobSkill(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(null=True, blank=False)

    class Meta:
        verbose_name = "Job Skill"
        verbose_name_plural = "Job Skills"

    def __str__(self):
        return self.name

    def get_unique_slug(self):
        counter = 0
        slug = slugify(unidecode(self.name))
        new_slug = slug
        while JobSkill.objects.filter(slug=new_slug).exists():
            counter += 1
            new_slug = "{}-{}".format(slug, counter)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = self.get_unique_slug()
        else:
            job_skill = JobSkill.objects.get(slug=self.slug)
            if job_skill.name != self.name:
                self.slug = self.get_unique_slug()
        super(JobSkill, self).save(*args, **kwargs)

    @property
    @admin.display(description="Related Job Posts")
    def get_related_job_count(self):
        return self.job_posts.all().count()

    @property
    @admin.display(description="Related Candidates")
    def get_related_candidate_count(self):
        return self.candidates.all().count()


class JobPost(models.Model):
    LOCATION_CHOICES = [
        ("Istanbul/Office", "Istanbul/Office"),
        ("Ankara/Office", "Ankara/Office"),
        ("Remote", "Remote"),
    ]
    TYPE_CHOICES = [
        ("FT", "Full-Time"),
        ("PT", "Part-Time"),
        ("IS", "Internship"),
    ]
    name = models.CharField(max_length=512)
    description = models.TextField()
    skills = models.ManyToManyField(JobSkill, "job_posts")
    location = models.CharField(choices=LOCATION_CHOICES, max_length=15)
    job_type = models.CharField(choices=TYPE_CHOICES, max_length=2)
    slug = models.SlugField(null=True, blank=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    candidates = models.ManyToManyField(CandidateProfile, "job_posts")

    class Meta:
        verbose_name = "Job Post"
        verbose_name_plural = "Job Posts"

    def __str__(self):
        return self.name

    def get_unique_slug(self):
        counter = 0
        slug = slugify(unidecode(self.name))
        new_slug = slug
        while JobPost.objects.filter(slug=new_slug).exists():
            counter += 1
            new_slug = "{}-{}".format(slug, counter)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = self.get_unique_slug()
        else:
            job_post = JobPost.objects.get(slug=self.slug)
            if job_post.name != self.name:
                self.slug = self.get_unique_slug()
        super(JobPost, self).save(*args, **kwargs)

    @property
    @admin.display(description="Candidate Count")
    def get_candidate_count(self):
        return self.candidates.all().count()

templates/index.html
{% extends 'utilities/base.html' %} {% load static %} {% block body %}

<div class="container">
  <h1 style="margin-bottom: 50px;">Welcome, {{request.user.get_full_name}}</h1>
  <div class="row">
    <div class="col-9">
      {% for job in job_posts %}
      <div class="row" style="border: 1px black solid; border-radius: 25px; margin: 10px 0px 10px 0px; padding: 5px;">
        <div class="col">
          <div class="row">
            <div class="col-10">
              <h3>{{job.name}}</h3>
            </div>
            <div class="col-2">
              <h6 style="float: right;">{{job.updated_date|date:"d-m-Y"}}</h6>
            </div>
          </div>
          <h6>{{job.location}} - {{job.get_job_type_display}}</h6>
          <p>{{job.description}}</p>
          <div style="display: flex; flex-direction: row;">
            {% for skill in job.skills.all %}
            <div style="border: 1px black solid; padding: 5px; margin: 0px 5px 0px 5px;">{{skill}}</div>
            {% endfor %}
          </div>
          {% if not job in request.user.candidate_profile.job_posts.all %}
            
         
          <form action="{% url 'candidate:apply_for_position' %}" method="post">
            {% csrf_token %}
            <input type="text" style="display: none;" name="appliedJobSlug" value="{{job.slug}}">
            <button class="btn btn-outline-success" style="margin-top: 10px; margin-bottom:10px;">Apply for this position</button>
          </form>
          
          {% else %}
          <button class="btn btn-success" style="margin-top: 10px; margin-bottom:10px;">You have already applied for this position</button>
          {% endif %}

        </div>
      </div>
      {% endfor %}
      
    </div>
    <div class="col-3">
      <h4>Search for open positions</h4>
      <form action="{% url 'index' %}" method="get">
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="Job title" aria-label="Job title" aria-describedby="btnSearchPositions" name="inputJobTitle">
          <button class="btn btn-outline-info" type="submit" id="btnSearchPositions">Search</button>
        </div>
        <div class="mb-3">
          <label for="inputSkills" class="form-label">Skills</label>

          <select class="form-select" name="inputSkills" id="inputSkills" multiple style="height: 200px;">
              {% for skill in job_skills %}
              <option value="{{skill.name}}" {% if skill.name in request.GET %} selected {% endif %}>{{skill}}</option>
              {% endfor %}
            </select>
            <p style="font-size: 12px; padding-top: 5px;"><mark>You can select multiple by using `CTRL + Click`</mark></p>
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}