apps/candidate/urls.py
from django.urls import path
from . import views

app_name = "candidate"
urlpatterns = [
    path("profile/", views.profile, name="profile"),
    path("update-password/", views.update_password, name="update_password"),
    path("apply/", views.apply_for_position, name="apply_for_position"),
    path("applied-jobs/", views.candidate_jobs, name="applied_jobs"),
    path("undo/", views.undo_for_position, name="undo_for_position"),
]

job_application_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views as core_views
from django.contrib.auth.views import (
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = (
    [
        path("admin/", admin.site.urls),
        # core urls
        path("", core_views.index, name="index"),
        path("register/", core_views.register, name="register"),
        path("login/", core_views.login, name="login"),
        path("logout/", core_views.logout, name="logout"),
        # candidate urls
        path("candidate/", include("apps.candidate.urls")),
        # password reset urls derived from core Django
        path(
            "password/password_reset/done/",
            PasswordResetDoneView.as_view(
                template_name="password/password_reset_done.html",
            ),
            name="password_reset_done",
        ),
        path(
            "password/reset/<uidb64>/<token>/",
            PasswordResetConfirmView.as_view(
                template_name="password/password_reset_confirm.html",
            ),
            name="password_reset_confirm",
        ),
        path(
            "password/reset/done/",
            PasswordResetCompleteView.as_view(
                template_name="password/password_reset_complete.html",
            ),
            name="password_reset_complete",
        ),
        path("password/reset", core_views.password_reset, name="password_reset")
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

apps/candidate/models.py
from django.db import models
from django.contrib.auth.models import User
from unidecode import unidecode
from django.template.defaultfilters import slugify
from django.contrib import admin


class CandidateProfile(models.Model):
    user = models.OneToOneField(User, models.CASCADE, related_name="candidate_profile")
    bio = models.TextField()
    skills = models.ManyToManyField("candidate.JobSkill", "candidates")

    class Meta:
        verbose_name = "Candidate Profile"
        verbose_name_plural = "Candidate Profiles"

    def __str__(self):
        return self.user.username


class JobSkill(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(null=True, blank=False)

    class Meta:
        verbose_name = "Job Skill"
        verbose_name_plural = "Job Skills"

    def __str__(self):
        return self.name

    def get_unique_slug(self):
        counter = 0
        slug = slugify(unidecode(self.name))
        new_slug = slug
        while JobSkill.objects.filter(slug=new_slug).exists():
            counter += 1
            new_slug = "{}-{}".format(slug, counter)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = self.get_unique_slug()
        else:
            job_skill = JobSkill.objects.get(slug=self.slug)
            if job_skill.name != self.name:
                self.slug = self.get_unique_slug()
        super(JobSkill, self).save(*args, **kwargs)

    @property
    @admin.display(description="Related Job Posts")
    def get_related_job_count(self):
        return self.job_posts.all().count()

    @property
    @admin.display(description="Related Candidates")
    def get_related_candidate_count(self):
        return self.candidates.all().count()


class JobPost(models.Model):
    LOCATION_CHOICES = [
        ("Istanbul/Office", "Istanbul/Office"),
        ("Ankara/Office", "Ankara/Office"),
        ("Remote", "Remote"),
    ]
    TYPE_CHOICES = [
        ("FT", "Full-Time"),
        ("PT", "Part-Time"),
        ("IS", "Internship"),
    ]
    name = models.CharField(max_length=512)
    description = models.TextField()
    skills = models.ManyToManyField(JobSkill, "job_posts")
    location = models.CharField(choices=LOCATION_CHOICES, max_length=15)
    job_type = models.CharField(choices=TYPE_CHOICES, max_length=2)
    slug = models.SlugField(null=True, blank=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    is_active = models.BooleanField(default=True)
    candidates = models.ManyToManyField(CandidateProfile, "job_posts")

    class Meta:
        verbose_name = "Job Post"
        verbose_name_plural = "Job Posts"

    def __str__(self):
        return self.name

    def get_unique_slug(self):
        counter = 0
        slug = slugify(unidecode(self.name))
        new_slug = slug
        while JobPost.objects.filter(slug=new_slug).exists():
            counter += 1
            new_slug = "{}-{}".format(slug, counter)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            self.slug = self.get_unique_slug()
        else:
            job_post = JobPost.objects.get(slug=self.slug)
            if job_post.name != self.name:
                self.slug = self.get_unique_slug()
        super(JobPost, self).save(*args, **kwargs)

    @property
    @admin.display(description="Candidate Count")
    def get_candidate_count(self):
        return self.candidates.all().count()

apps/candidate/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import JobPost, JobSkill
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods


@login_required
def profile(request):
    if request.method == "POST":
        # get data
        username = request.POST.get("inputEmail")
        first_name = request.POST.get("inputFirstName")
        last_name = request.POST.get("inputLastName")
        bio = request.POST.get("inputBio")
        skills = request.POST.getlist("inputSkills")

        # update user with new data
        user = request.user
        user.username = username
        user.email = username
        user.first_name = first_name
        user.last_name = last_name
        user.candidate_profile.bio = bio
        user.candidate_profile.skills.set(skills)
        # error check for unique username & email

        try:
            user.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f"{request.user.username} successfully updated.",
            )
        except Exception as e:
            messages.add_message(
                request,
                messages.WARNING,
                f"{request.user.username} couldn't update. Error: {e}",
            )
        return redirect("candidate:profile")

    job_skills = JobSkill.objects.all()
    return render(request, "candidate/profile.html", {"job_skills": job_skills})


@login_required
def update_password(request):
    if request.method == "POST":
        # get data
        old_password = request.POST.get("inputOldPassword")
        new_password = request.POST.get("inputNewPassword")
        re_new_password = request.POST.get("inputReNewPassword")
        if not request.user.check_password(old_password):
            messages.add_message(
                request, messages.WARNING, "You have to use the exact old password"
            )
            return redirect("candidate:update_password")
        if not new_password == re_new_password:
            messages.add_message(
                request, messages.WARNING, "New passwords doesn't match."
            )
            return redirect("candidate:update_password")
        request.user.set_password(new_password)
        request.user.save()
        messages.add_message(
            request,
            messages.SUCCESS,
            "Password has been updated successfully. You can use it for next logins.",
        )
        return redirect("logout")
    return render(request, "candidate/update_password.html")


@login_required
@require_http_methods(["POST"])
def apply_for_position(request):
    applied_job_slug = request.POST.get("appliedJobSlug")
    applied_job = get_object_or_404(JobPost, slug=applied_job_slug)
    request.user.candidate_profile.job_posts.add(applied_job)
    messages.add_message(
        request, messages.SUCCESS, "You have successfully applied to the position."
    )
    return redirect("index")


@login_required
@require_http_methods(["POST"])
def undo_for_position(request):
    applied_job_slug = request.POST.get("appliedJobSlug")
    applied_job = get_object_or_404(JobPost, slug=applied_job_slug)
    request.user.candidate_profile.job_posts.remove(applied_job)
    messages.add_message(
        request, messages.SUCCESS, "You have successfully undid application for the position."
    )
    return redirect("candidate:applied_jobs")


@login_required
def candidate_jobs(request):
    user_jobs = request.user.candidate_profile.job_posts.all()
    return render(request, "candidate/applied_jobs.html", {"job_posts": user_jobs})

templates/candidate/applied_jobs.html
{% extends 'utilities/base.html' %} {% load static %} {% block body %}

<div class="container">
  <h1 style="margin-bottom: 50px;">Your applied jobs are here</h1>
  <div class="row">
    <div class="col-12">
        {% if job_posts %}
        {% for job in job_posts %}
        <div class="row" style="border: 1px black solid; border-radius: 25px; margin: 10px 0px 10px 0px; padding: 5px;">
          <div class="col">
            <div class="row">
              <div class="col-12">
                <h3>{{job.name}}</h3>
              </div>
              <div class="col-2">
                <h6 style="float: right;">{{job.updated_date|date:"d-m-Y"}}</h6>
              </div>
            </div>
            <h6>{{job.location}} - {{job.get_job_type_display}}</h6>
            <p>{{job.description}}</p>
            <div style="display: flex; flex-direction: row;">
              {% for skill in job.skills.all %}
              <div style="border: 1px black solid; padding: 5px; margin: 0px 5px 0px 5px;">{{skill}}</div>
              {% endfor %}
            </div>
  
            <button class="btn btn-success" style="margin-top: 10px; margin-bottom:10px;">You have already applied for this position</button>
            
            <form action="{% url 'candidate:undo_for_position' %}" method="post" style="float:right;">
              {% csrf_token %}
              <input type="text" style="display: none;" name="appliedJobSlug" value="{{job.slug}}">
              <button class="btn btn-outline-danger" style="margin-top: 10px; margin-bottom:10px;">Undo application for this position</button>
            </form>
          </div>
        </div>
        {% endfor %}
        {% else %}
        <h1>You haven't applied any job.</h1>
        {% endif %}
    </div>
  </div>
</div>
{% endblock %}

templates/candidate/profile.html
{% extends 'utilities/base.html' %} {% load static %} {% block body %}
<div class="container">
  <div class="row">
    <div class="col-3"></div>
      <div class="col-6">
        <h3>Profile & Preferences</h3>
      <form method="post" action="{% url 'candidate:profile' %}">
        {% csrf_token %}
        <div class="mb-3">
          <label for="inputEmail" class="form-label">Email</label>
          <input
            type="email"
            class="form-control"
            id="inputEmail"
            name="inputEmail"
            value="{{request.user.username}}"
          />
        </div>
        <div class="mb-3">
          <label for="inputFirstName" class="form-label">First Name</label>
          <input
            type="text"
            class="form-control"
            id="inputFirstName"
            name="inputFirstName"
            value="{{request.user.first_name}}"
          />
        </div>
        <div class="mb-3">
          <label for="inputLastName" class="form-label">Last Name</label>
          <input
            type="text"
            class="form-control"
            id="inputLastName"
            name="inputLastName"
            value="{{request.user.last_name}}"
          />
        </div> 
        <div class="mb-3">
          <label for="inputBio" class="form-label">Bio</label>
          <textarea class="form-control" id="inputBio" rows="3" name="inputBio">{{request.user.candidate_profile.bio}}</textarea>
        </div>
        <div class="mb-3">
            <label for="inputSkills" class="form-label">Skills</label>
            <p style="font-size: 12px;"><mark>You can select multiple by using `CTRL + Click`</mark></p>
            <select class="form-select" name="inputSkills" id="inputSkills" multiple style="height: 200px;">
                {% for skill in job_skills %}
                <option value="{{skill.id}}" {% if skill in request.user.candidate_profile.skills.all %} selected {% endif %} >{{skill}}</option>
                {% endfor %}
              </select>
          </div>
        <button type="submit" class="btn btn-success">Update Profile</button>
      </form>
      <br>
      <a href="{% url 'candidate:update_password' %}">
        <button type="submit" class="btn btn-info" style="color: white;">Redirect to Update Password >></button>
      </a>
    </div>
    <div class="col-3"></div>
  </div>
</div>
{% endblock %}

templates/candidate/update_password.html
{% extends 'utilities/base.html' %} {% load static %} {% block body %}
<div class="container">
  <div class="row">
    <div class="col-3"></div>
     <div class="col-6">
        <h3>Update Password</h3>
      <form method="post" action="{% url 'candidate:update_password' %}">
        {% csrf_token %}
        <div class="mb-3">
          <label for="inputOldPassword" class="form-label">Old Password</label>
          <input
            type="password"
            class="form-control"
            id="inputOldPassword"
            name="inputOldPassword"
          />
        </div> 
        <div class="mb-3">
          <label for="inputNewPassword" class="form-label">New Password</label>
          <input
            type="password"
            class="form-control"
            id="inputNewPassword"
            name="inputNewPassword"
          />
        </div>
       
        <div class="mb-3">
          <label for="inputReNewPassword" class="form-label">Re-New Password</label>
          <input
            type="password"
            class="form-control"
            id="inputReNewPassword"
            name="inputReNewPassword"
          />
        </div>
        <button type="submit" class="btn btn-success">Update Password</button>
      </form>
      <br>
      <a href="{% url 'candidate:profile' %}">
        <button type="submit" class="btn btn-info" style="color: white;">Redirect to Update Profile >></button>
      </a>
    </div>
    <div class="col-3"></div>
  </div>
</div>
{% endblock %}